### ISSUE TITLE
Unable to create portfolio - empty list of currencies 

### ISSUE THREAD

**Issue by carlosleocadio** [bocabitlabs/buho-stocks#28]
The list currencies query is returning no answer, resulting in a empty list of options shown in the UI.
Attaching screenshot.

<img width="1301" alt="Screenshot 2022-10-17 at 21 00 37" src="https://user-images.githubusercontent.com/29845789/196260949-c46dd609-896e-43a5-ad48-5c53c6f7bd22.png">

I am running the application using the latest docker image available.

**Comment by carlosleocadio** [comment]
I checked the DB content on my fresh installation and multiple tables used to list the available options in the UI are empty.
Example: currencies, sectors, super sectors and markets.
From my understanding those tables should be automatically populated using the content from .json files available in data subfolders, but apparently that is not happening.

**Comment by renefs** [comment]
Hi Carlos, thank you for opening this issue. It is the first one of the repo that is not made by me :)  

From your comment, I find indeed that are some things that are not clear about the initial setup. As you say, the tables are initially empty. You need to create a super user to access the admin panel on '/admin` and from there, you will be able to access and initialize all the application's data:

- currencies
- sectors
- super sectors
- etc

Just by clicking a button (this is an example for currencies):

![image](https://user-images.githubusercontent.com/1094547/196274682-e96b746f-3e54-422f-b7f3-6febdebfaa6a.png)

**Comment by carlosleocadio** [comment]
When I access the /admin I land on the admin login page, but it is unclear to me how to create the admin account. 
Could you please give me some guidelines on how to create such account?

<img width="521" alt="Screenshot 2022-10-17 at 23 26 50" src="https://user-images.githubusercontent.com/29845789/196287658-28a2f33d-71b0-4259-af11-dffa97a53cb7.png">

**Comment by renefs** [comment]
Hi Carlos, I made an update to the documentation and explained how to create the super user and populate the initial data. You can give it a try :)
