### ISSUE TITLE
blank page and error message: "Unable to fetch application's settings."

### ISSUE THREAD

**Issue by pi-2r** [bocabitlabs/buho-stocks#67]
Hello,
I am trying to launch the application locally.
I launch correctly the django server and the frontend. When I access the page (http://localhost:3000/), it loads and then an error message appears: "Unable to fetch application's settings."

How can I fix this?
Thanks

**Comment by renefs** [comment]
Hi @pi-2r , if you want to run the application locally without using `Docker`, you will need to perform some tasks that are done automatically when the application runs using `Docker`. I think in your case, you will need to run the database migrations manually:

```
python manage.py migrate
```

**Comment by pi-2r** [comment]
Hi @renefs, thanks you for your reply !
I followed the document correctly (https://bocabitlabs.github.io/buho-stocks/docs/development/using-virtual-environment).
Are there other elements or actions to be done ?

**Comment by renefs** [comment]
Can you check the application logs to see if there is an error on the backend? Also, the browser console logs would be helpful.

**Comment by pi-2r** [comment]
I get a "undefined" value in the request
![image](https://user-images.githubusercontent.com/2684587/236193068-7182bc1a-6455-4821-9a80-ce4974c7845c.png)

I need to define a few things in particular ?

**Comment by renefs** [comment]
Hi @pi-2r , found the problem. Since the client was migrated to Vite,I forgot that I was using `client/.env.local` file 🤦:

```
VITE_ENV = local
VITE_PORT = 3000
VITE_API_URL = http://127.0.0.1:8001
```

This will proxy the API requests. However, I added it to the repo.

**Comment by renefs** [comment]
And BTW I updated the development docs on virtual environment :) https://bocabitlabs.github.io/buho-stocks/docs/development/using-virtual-environment

**Comment by pi-2r** [comment]
Hi @renefs , it's work now for me.
Thanks you !
